### ISSUE TITLE
Having trouble discovering devices (Windows 10, python 3.8)

### ISSUE THREAD

**Issue by briantho** [mikelawrence/aiosenseme#3]
I have tried both using "pip install aiosenseme" and cloning from github, and running setup.py. Both Result in the same error discovering. Both versions have a problem discovering devices. Here is the debug info taken from running 
aiosenseme --debug --discover

```
DEBUG:aiosenseme.discovery:Added coroutine callback
DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.111.225
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.107.37
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Listening on 10.4.44.157
DEBUG:aiosenseme.discovery:Protocol error on 10.4.44.157
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 526, in _loop_writing
    self._write_fut = self._loop._proactor.sendto(self._sock,
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 510, in sendto
    ov.WSASendTo(conn.fileno(), buf, flags, addr)
OSError: [WinError 10022] An invalid argument was supplied

DEBUG:aiosenseme.discovery:Discovery broadcast on 10.4.44.157
DEBUG:aiosenseme.discovery:Listener closed on 10.4.44.157
DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.178.32
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Broadcaster task cancelled

```
Please let me know how to fix this, or is this a bug. Thanks

Also, running aiosenseme --discover does nothing

**Comment by mikelawrence** [comment]
So the 169.254.111.225 is a self assigned address and clearly will not work.

Is your fan on the same network as this windows machine 10.4.44.157? If you are running a VLAN it will not work. Discovery requires UDP broadcast packet and by design they do not traverse networks without some wrangling in your router. You could provide the output of "ipconfig".

Are running powershell/command line or WSL?

**Comment by briantho** [comment]
I'm running this via Windows command prompt. The fan is on the same network, as the laptop from which I'm testing. My main router is a Ubiquity EdgeRouter Pro, but I don't use any vlans. my ip address is 10.4.44.157. I tried disabling my computers firewall, but I'm still getting the same error.  I have no clue what the 169.254.111.225 is. 

here is the output from ipconfig
C:\WINDOWS\system32>ipconfig

Windows IP Configuration


Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 12:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 10.4.44.157
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.4.44.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

**Comment by mikelawrence** [comment]
The 169.254.111.225 can come from many things like a VPN connection that isn't connected. 
What fan do you have (i.e. Haiku L Series)? 
Have you setup the fan with the Haiku by BAF app on your phone?

**Comment by briantho** [comment]
Yes, I just checked the fan app. It is able to communicate, with the app. I have 2 haiku H/I series according to the app, and they are both firmware 2.70.  I also tried selecting the fan by ip address, but it's still not working. The app says the fan's ip address is 10.4.44.127
Here is what i get when running aiosenseme -n 10.4.44.127

Name/Room/IP address '10.4.44.127' not found

here is the debug output

```
aiosenseme -n 10.4.44.127 --debug
DEBUG:aiosenseme.discovery:Listening on 10.4.44.145
DEBUG:aiosenseme.discovery:Protocol error on 10.4.44.145
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 526, in _loop_writing
    self._write_fut = self._loop._proactor.sendto(self._sock,
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 510, in sendto
    ov.WSASendTo(conn.fileno(), buf, flags, addr)
OSError: [WinError 10022] An invalid argument was supplied

DEBUG:aiosenseme.discovery:Discovery broadcast on 10.4.44.145
DEBUG:aiosenseme.discovery:Listener closed on 10.4.44.145
DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.111.225
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.107.37
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Listening on 10.4.44.157
DEBUG:aiosenseme.discovery:Protocol error on 10.4.44.157
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 526, in _loop_writing
    self._write_fut = self._loop._proactor.sendto(self._sock,
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 510, in sendto
    ov.WSASendTo(conn.fileno(), buf, flags, addr)
OSError: [WinError 10022] An invalid argument was supplied

DEBUG:aiosenseme.discovery:Discovery broadcast on 10.4.44.157
DEBUG:aiosenseme.discovery:Listener closed on 10.4.44.157
DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.169.79
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

DEBUG:aiosenseme.discovery:Create datagram endpoint error on 169.254.178.32
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\aiosenseme-0.4.3-py3.8.egg\aiosenseme\discovery.py", line 209, in _create_endpoints
    await loop.create_datagram_endpoint(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [WinError 10049] The requested address is not valid in its context

Name/Room/IP address '10.4.44.127' not found
DEBUG:aiosenseme.discovery:Broadcaster task cancelled
```

**Comment by mikelawrence** [comment]
Even though you typed in an address with the following command ```aiosenseme -n 10.4.44.127 --debug``` it still must be discovered for it to work. At some point I plan on adding actual lookup by IP address thus bypassing the discovery. Discovery is sometimes hit-or-miss. Meaning it just doesn't work sometimes but in most cases trying later helps.

Can you try a different machine? Maybe a Raspberry Pi or Mac or WSL in Windows to see if your fans can be discovered.

**Comment by briantho** [comment]
Ok, I got it working on windows and a ubuntu virtual machine. The problem it seems like is that aiosenseme doesn't work with the latest python 3.8.5. At first I tried running aiosenseme on a ubuntu virtual machine and it ran without issues, everything was detected. I saw that this virtual machine was running python 3.6.11. So, I tried uninstalling python 3.8.5 on my windows machine, and installing 3.6.11. After that aiosenseme is now working perfectly on my windows machine. Can you test and try to get this working with 3.8.5? Thanks

**Comment by mikelawrence** [comment]
Very interesting. Thanks for narrowing it down! 

I am kinda busy for the next few days but I'll get to this soon.

**Comment by briantho** [comment]
No problem, take your time. I'm glad i was able to help. I also just checked, and its still works with 3.7.8
Something with 3.8.5 must have broken compatibility

**Comment by mikelawrence** [comment]
Release v0.4.4 should fix this problem. I changed the default event loop for Windows and I am a bit concerned about additional problems this may create. This fix does not affect Linux or MacOS.

My testing on Windows Python 3.8.5 64-bit was successful. Let me know how it works for you.

Sorry this fix took so long.

**Comment by briantho** [comment]
Seems to work™

Sorry it took me a while to respond.  I tested on windows 10, with python 3.85. It looks like its working. Both my haiku fans were detected with the -d option. I just saw they released a new python 3.9, but haven't tested it yet, hope that will work. Anyway, thanks for fixing this.

**Comment by briantho** [comment]
Actually, I think there is still one more bug I think is still present that wasn't there when i tested with python 3.7.5 and aiosenseme 4.3 
I don't exactly remember, but when i run 

`aiosenseme -n "Master Bedroom 1 Fan" --fan off`

I get this responce back 

Master Bedroom 1 Fan
  Room Name: Master Bedroom 1, Room Type: Master Bedroom
  Model: Haiku Fan without light, FW Version: 2.7.0
  IP Addr: 10.4.44.113, MAC Addr: 20:F8:5E:F7:01:74
  Token: 2b57e6c6-fe00-460a-8881-3de0b7b23c9e
State: Fan is off, Light is off
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\aiosenseme-script.py", line 11, in <module>
    load_entry_point('aiosenseme==0.4.4', 'console_scripts', 'aiosenseme')()
  File "c:\program files\python38\lib\site-packages\aiosenseme\scripts\commandline.py", line 319, in cli
    loop.run_until_complete(task)
  File "c:\program files\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\program files\python38\lib\site-packages\aiosenseme\scripts\commandline.py", line 312, in process_args
    device.stop()
  File "c:\program files\python38\lib\site-packages\aiosenseme\device.py", line 804, in stop
    self._listener_task.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'



as you can see,  
Room Name: Master Bedroom 1, Room Type: Master Bedroom
  Model: Haiku Fan without light, FW Version: 2.7.0
  IP Addr: 10.4.44.113, MAC Addr: 20:F8:5E:F7:01:74
  Token: 2b57e6c6-fe00-460a-8881-3de0b7b23c9e
State: Fan is off, Light is off 

is correct, but what about everything below that?

This happens when i use the -n option by itself too without any additional parameters. Is this the "additional" problems you mentioned?

**Comment by mikelawrence** [comment]
Thanks for reporting this bug! It is fixed now with aiosenseme v0.4.5.

**Comment by briantho** [comment]
No Problem. looks like it's working correctly now. Thanks for fixing this
